source 'https://rubygems.org'

gem 'json'
gem 'nokogiri'
gem 'sequel'
gem 'sqlite3'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'sinatra-sequel'
gem 'itamae', git: 'git@github.com:itamae-kitchen/itamae.git'
gem 'unicorn'
